[metadata]
name = "{{PACK_NAME}}"
description = "Atlas demo pack repository."

[versions]
mc = "1.20.1"
modloader = "fabric"
modloader_version = "0.15.11"

[cli]
pack_id = "{{PACK_ID}}"
default_channel = "dev"
