[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
prost = "0.13"
zstd = "0.13"
thiserror = "1.0"

[build-dependencies]
prost-build = "0.13"
protoc-bin-vendored = "3"
